### ISSUE TITLE
[Passive] GOLDEN WATCH

### ISSUE THREAD

**Issue by gokiburikin** [FacemanFoothand/abpack3#11]
Enemies move slower the longer they are alive, does not affect bosses

**Art**: Complete

![collectible_goldwatch](https://cloud.githubusercontent.com/assets/24993635/24420771/327194f6-13b1-11e7-87a0-6986fd25da97.png)

**Code**: WIP

**Comment by FacemanFoothand** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GOLD WATCH: Enemies/Isaac Slow With Age](https://trello.com/c/KRxXJpQi/10-gold-watch-enemies-isaac-slow-with-age)
