### ISSUE TITLE
[Passive] ROCKET SHOES

### ISSUE THREAD

**Issue by gokiburikin** [FacemanFoothand/abpack3#12]
Speed + 0.5, instantly reach top speed

**Art**:  Complete

![collectible_rocketshoes](https://cloud.githubusercontent.com/assets/24993635/24458878/6e61eeba-1457-11e7-84fe-eeb6423ba9af.png)

**Costume:** WIP

**Code**: Completed

**Comment by FacemanFoothand** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ROCKET SHOES: Max Acceleration](https://trello.com/c/GTjk6yvy/115-rocket-shoes-max-acceleration)
