### ISSUE TITLE
[Passive] CORN COB

### ISSUE THREAD

**Issue by jtmcginnis** [FacemanFoothand/abpack3#13]
Chance to spawn friendly dip when special tear hits.

**Code**: WIP
**Art**: Complete

![collectible_corncob](https://cloud.githubusercontent.com/assets/24993635/24420818/5c836472-13b1-11e7-9bd7-4c55b99e4cf7.png)

**Animation**: Tear Animation Needed

**Comment by FacemanFoothand** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CORN SHOT: Chance to spawn a friendly dip on special tear hit](https://trello.com/c/pvmOdZ14/173-corn-shot-chance-to-spawn-a-friendly-dip-on-special-tear-hit)

**Comment by FacemanFoothand** [comment]
Item renamed to Corn Cob
