### ISSUE TITLE
[Active] MAGIC PENNY

### ISSUE THREAD

**Issue by FacemanFoothand** [FacemanFoothand/abpack3#26]
_3 Charge_

Drop a penny on the ground that magnetizes other consumables (possibly enemies).

Art: Complete
![collectible_magicpenny](https://cloud.githubusercontent.com/assets/24993635/25401770/dfdeb124-29b3-11e7-90d8-cf58cbe30e05.png)
Dropped Animation: Not Started

Code: Not Started

**Comment by Meowlala** [comment]
Might be good idea to cut due to being similar in function to the Black Hole.
