### ISSUE TITLE
[Passive] Smart Bombs

### ISSUE THREAD

**Issue by jtmcginnis** [FacemanFoothand/abpack3#3]
On placing a bomb anywhere in a room, if there is a secret room adjacent to the current room, a smart bomb will be automatically placed at the secret room entrance (does not consume an extra bomb)

+5 Bombs

Sprite: WIP
Costume(Including anm2): Not started

Code: WIP

**Comment by FacemanFoothand** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SMART BOMBS: Bombs Find Secrets](https://trello.com/c/Y0rfTOxQ/8-smart-bombs-bombs-find-secrets)
