### ISSUE TITLE
[Passive] COMET TEARS

### ISSUE THREAD

**Issue by KyoZM** [FacemanFoothand/abpack3#34]
Shot speed down + Homing. Tears have a large trail that will burn enemies on contact

**Comment by FacemanFoothand** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [COMET TEARS: Shot speed down + Homing. Tears have a large trail that will burn enemies on contact](https://trello.com/c/4Ux88ccC/29-comet-tears-shot-speed-down-homing-tears-have-a-large-trail-that-will-burn-enemies-on-contact)
