### ISSUE TITLE
[Active] Russian Roulette

### ISSUE THREAD

**Issue by debugman18** [FacemanFoothand/abpack3#4]
Will either hurt the player, do nothing, or kill all enemies (even bosses) in a room

Sprite: WIP / Multiple Stages of Item Needed
SFX: Not started (Click, muffled shot + loud shot needed)

Code: WIP

**Comment by FacemanFoothand** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [RUSSIAN ROULETTE: Hurts Player, Enemy Or Do Nothing](https://trello.com/c/jHuycA1q/41-russian-roulette-hurts-player-enemy-or-do-nothing)

**Comment by cathery1** [comment]
stinky
