### ISSUE TITLE
[Passive] COSMOS

### ISSUE THREAD

**Issue by gokiburikin** [FacemanFoothand/abpack3#8]
Gives the player 3 orbitals,
1: Mercury; orbits close dealing fire damage on contact
2: Venus; orbits further away/slower, charm effect on contact
3: Pluto; orbits furthest/slowest, chance to freeze on contact

**Art**: Complete

![collectible_cosmos](https://cloud.githubusercontent.com/assets/24993635/24428629/4e369f90-13cc-11e7-883b-6ae3bc47f3c6.png)

**Code**: Complete

**Comment by FacemanFoothand** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [THE COSMOS: Planet Orbitals](https://trello.com/c/VfDP62Kk/9-the-cosmos-planet-orbitals)
